server:
  port: 8761

spring:
  application:
    name: registry

security:
  basic:
    enabled: true               #  开启基于HTTP basic的认证
  user:
    #name: admin
    #password: 123
    name: admin
    password: 123

eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0


cola:
  swagger2:
    enable: true
    base-package: com.honvay.cola
    title : Cola-Cloud
    description: Cola cloud Restful API docs
    termsOfServiceUrl : http://localhost:4000
    version: 1.0
    apiName: Authorization
    apiKeyName: Authorization