spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  application:
    name: config

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:123@localhost:8761/eureka/

server:
  port: 8888

security:
  basic:
    enabled: true               #  开启基于HTTP basic的认证 
  user:
    #name: admin                # 配置登录的账号是user
    #password: 123            # 配置登录的密码是password123
    name: admin                                     # 配置登录的账号是admin
    password: 123                                   # 配置登录的密码是123
